### PR TITLE
Update direction numbers

### PR DESCRIPTION
**Pull request by JohnAdders**
Update direction numbers to latest ones from 
http://web.maths.unsw.edu.au/~fkuo/sobol/
Extends supported dimensions to 21201.

### CODE REVIEW

**Comment by JohnAdders** [comment]
Julia 0.4 tests failing quite badly, I'm not clear what's going on there.
On 0.5 and 0.7 the errors relative to the paper are smaller, how do you wish to proceed as I don't think there are comparable values for the test integrals in the new paper. How do you wish to proceed?

**Comment by stevengj** [comment]
Do they have a reference implementation?  The best thing would just be to generate, say, 1000 numbers in the sequence and then compare the next 3 numbers.

I never liked the "test integral" test, but used it because then I could compare to the published values in the papers.   The same tests are unlikely to succeed with new direction numbers, because they test specific values of the integration error calibrated to the original direction number.

**Comment by JohnAdders** [comment]
Yes there is a sobol.cc program which spits out the generated sequence with the slight annoyance that the sequence includes all zeros as the first item.  How about I add tests for the  1024-1026 samples for dimensions 2, 5, 10, 100?

**Comment by stevengj** [comment]
Should it start with the origin?

We should also test the max dimensions. We can put the data in a file, it’s not that big.

**Comment by JohnAdders** [comment]
I've updated the tests and got the tests passing on all versions.  Should be ready to merge.  Let me know if there is anything else you need.

**Comment by stevengj** [comment]
LGTM, thanks!

**Pull request merged**
